# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-09-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_content_doc_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
